### ISSUE TITLE
Minify and optimize bundle.js

### ISSUE THREAD

**Issue by gfronza** [porthos-rpc/porthos-dashboard#2]
The current `bundle.js` has 2MB 👎

**Comment by xRahul** [comment]
I've optimized my own builds before.. I'll work on it!

**Comment by xRahul** [comment]
PR created- https://github.com/porthos-rpc/porthos-dashboard/pull/3

Plus you can use gzip to serve the bundle.js via your server. I've found that further reduces the size by around 4x. I did that and the size was reduced from 1.6MB to ~400KB

**Comment by gfronza** [comment]
@xRahul Currently the golang is serving the bundle. But for production it would be better to put a nginx in front of it. There I can add gzip and other stuff with more flexibility.
